### ISSUE TITLE
Injection of Transport for Surface Tension 

### ISSUE THREAD

**Issue by himakarganti** [code-mphi/ECOGEN#11]
I am trying to inject a liquid with surface tension on an unstructured grid with airflow. I am including the surface tension physics using the color transport. However, when I try to run,  I get the following error:
```
Exception sur file XML : attribut introuvable 
****************************************
 file XML concerne : './libTests/myRuns/liquidInjectSurfTens/initialConditionsV4.xml'
 infos sur exception code source :
  file : 'src/BoundConds/BoundCondInj.cpp'
  ligne : 135
 name de l attribut recherche : 'Not enough transport equations in inj BC'
```
Here is my input for the liquid phase in the initial conditions file:
```
<boundCond name="jet" type="injection" number="4">
    <dataInjection m0="50000"/>
    <dataFluid EOS="IG_air.xml" density="1." pressure="1.01e5" alpha="0."/>
    <dataFluid EOS="SG_liquidForSurfaceTensionCases.xml" density="1000." pressure="1.01e5" alpha="1."/>
    <transport name="color" value="1."/>
</boundCond>
```
Can someone please let me know how to include the missing transport equation for injection BC?

**Comment by kevinschmidmayer** [comment]
Dear ECOGEN user,

Thank you very much for sharing your ECOGEN experience, we are very happy to count you among the ECOGEN user community!

Your message seems to require troubleshooting or assistance in installing the environment required for ECOGEN, using or modifying the input data files for running ECOGEN. Unfortunately, the ECOGEN team is too small to have a thorough look at your problem.
We can therefore only advise you to read again very carefully the documentation at https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/index.html. 

We truly hope that you will solve this problem quickly in order to have a good experience with ECOGEN!
The ECOGEN team
