### ISSUE TITLE
Need output files for both XML & GNU formats

### ISSUE THREAD

**Issue by himakarganti** [code-mphi/ECOGEN#13]
Hello ECOGEN developers & users,

I am trying to run an unstructured grid in 3D and need the output datafiles of both GNU & XML (Paraview/ Visit) formats. Right now it seems we can only choose only one format for the output datafiles. Running the same case twice for data generation in two different formats for 3D cases will be really computationally expensive for my case. Is there a way we can specify ECOGEN to generate datafiles in both formats? i.e.:

`<outputMode format="XML" binary="false" />`
and
`<outputMode format="GNU" binary="false" />`

Need datafiles from both formats simultaneously for the same simulation.

**Comment by kevinschmidmayer** [comment]
Dear ECOGEN user,

This option does not exist in ECOGEN and we are sorry but this option is not in our prioritized developments to do.
Anyway, we encourage you to join the developer community: https://github.com/code-mphi/ECOGEN/watchers.
Do not hesitate to submit modification through this media following instructions at https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap6_developersGuide_Chapter.html. This is a good way to have your contribution include in the open-source platform.

We truly hope that you will solve this problem quickly in order to have a good experience with ECOGEN!
The ECOGEN team
