### ISSUE TITLE
How to install ECOGEN on Windows system？

### ISSUE THREAD

**Issue by zhao-xt** [code-mphi/ECOGEN#15]

**Comment by kevinschmidmayer** [comment]
Dear ECOGEN user,

Sorry for the late reply.

Your message seems to require troubleshooting or assistance in installing the environment required for ECOGEN, using or modifying the input data files for running ECOGEN. Unfortunately, the ECOGEN team is too small to have a thorough look at your problem.
We can therefore only advise you to read again very carefully the documentation at https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/index.html.
Further, we provide an installation procedure for a linux system and not for a Windows one. Indeed, there are numerous ways to compile and execute a C++ code on Windows and the installation procedure may highly depend on the version of your system.

We truly hope that you will solve this problem quickly in order to have a good experience with ECOGEN!
The ECOGEN team
