### ISSUE TITLE
Add time factor in simulation

### ISSUE THREAD

**Issue by amantr17** [code-mphi/ECOGEN#18]
Dear All,
Please help me out in following coding stuff. I am working on problem - flow of air bubble inside water.In coding by ECOGEN,  I need to add the air bubble after the water/fluid reached steady state flow. Can ECOGEN allows us to introduce that bubble after some time, for example 5 sec.
Kindly suggest me the changes which I need to do.
I am attaching my codes below.

Thanks & Regards.
Aman Tripathi
[geo.zip](https://github.com/code-mphi/ECOGEN/files/8239286/geo.zip)

Ph.D. Scholar,
IISER Bhopal, India

**Comment by JorisCaze** [comment]
Dear @amantr17, 

One of the easiest way to setup this kind of flow configuration would be to run the simulation with only the water first, reach the steady state and use the final flow values to initialize the test case with the air bubble.

To do so, you could set the liquid to be pure with `alpha = 1` in agreement with the option `alphaNull = true` in the *modelVX.xml* file.
Be careful to set properly your boundary conditions in the file *initialConditionsVX.xml* because currently the boundaries *3* and *4* are defined twice.

Regards, 
Joris

**Comment by amantr17** [comment]
Dear Joris,
               Thanks for your valuable suggestions and efforts. May I know why these codes are not running using MPI command using multi core CPU. They are running on single CPU core by wrtting command ./ECOGEN on terminal

If we use command- mpirun -np 2 ECOGEN, then it shows folloeing error:

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node User-PC exited on signal 11 (Segmentation fault).

Please help me out so that we can save our simulation time specially while using AMR geometry cases.

Thanks & Regards.
Aman

**Comment by JorisCaze** [comment]
Dear @amantr17, 

It seems your installation of OpenMPI is not properly configured.
I would recommend to reinstall the OpenMPI library and try again. 
Check the installation instruction of the [documentation](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap2_1installation.html) for more details about this.
In order to check if the library was installed correctly you could try a simple *hello world* code:
- Download the `helloWorld.cpp` code
[helloWorld.zip](https://github.com/code-mphi/ECOGEN/files/8360980/helloWorld.zip)
- Compile it with OpenMPI using `mpiccx -o helloWorld helloWorld.cpp`
- Run it on several CPUs using `mpirun -np 4 helloWorld`

If you encounter any errors, it will confirm that your OpenMPI installation is not done correctly, in this case you will have to check with the [OpenMPI developpers](https://www.open-mpi.org/) for recommendations on your problem.

Regards, 
Joris
