### ISSUE TITLE
How to incorporate mass transfer

### ISSUE THREAD

**Issue by syam-s** [code-mphi/ECOGEN#26]
Hello ECOGEN team,
I would like to incorporate mass transfer into the ECOGEN since I am interested in the evaporation of the liquid phase. It would be very helpful if you could give some suggestions on how to incorporate the mass transfer into the additional physics term of ECOGEN.
Thank you.

**Comment by code-mphi** [comment]
Dear Syam,

To my knowledge and without entering too many details, there are two
variants to introduce phase change. The first uses relaxations and a first
version of it is already implemented within ECOGEN. However, the current
version is not robust and work has been done on our side but it is not in
the available public version yet. Anyway, we implement this by using the
relaxation methods within ECOGEN. The second variant is to use source
terms, also using saturation conditions. For this one, it would certainly
make more sense to implement it through the source methods (such as what is
done for gravity), rather than the additional physics methods which are
more appropriate for splitted models.

Hope it helps and please keep us posted!

Best regards,
*Kevin Schmidmayer*
Permanent researcher
Inria Bordeaux Sud-Ouest - Project-team CAGIRE
Université de Pau et des Pays de l'Adour - Laboratoire de Mathématiques et
de leurs Applications de Pau
France
https://kevinschmidmayer.github.io/

**Comment by syam-s** [comment]
Thank you Kevin for the response. Is it possible to give some instructions (documentation) or literature on how to use or apply the relaxation method and source method for the implementation of the phase change part? Will the new phase change model be available in the next version?
