### ISSUE TITLE
Initialisation of pressure in liquid domain

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#29]
Dear all,

Greetings! I am facing an issue with the initial condition while simulating a bubble collapse problem. I understand that the default non-spherical bubble collapse test case in ECOGEN happens to be the same test case as given in this [article](https://www.researchgate.net/publication/363041799_Modelling_interactions_between_waves_and_diffused_interfaces). The initial pressure field is set according to a particular relation where pressure varies inversely with distance from the bubble centre outside the bubble. It has been mentioned in the article that this has been done being a realistic model, as well as avoid spurious pressure waves.

However in the test case, it seems to me that the liquid domain is uniformly initialised with pressure Pinf = 50.6 * 10^5 Pa, hence there is a discontinuity in terms of pressure across the interface. Apparently, this is generating a pressure wave as well, shown in the picture below: 

![Screenshot from 2022-12-14 12-10-39](https://user-images.githubusercontent.com/74908508/207530102-604fcd83-d1ec-4ed1-a57f-f5245a5db0a2.png)

Could someone please confirm whether this is the case? If yes, what changes should I make so as to initialise in accordance with the article?

Thanking you in advance,
Niranjan

**Comment by kevinschmidmayer** [comment]
Hi Niranjan,

You are right, the uploaded test case does have a discontinuity of pressure at the interface. The dynamics will still match Keller-Miksis but with an initial impulse instead of having the initial speed of the interface being null. Note that the pressure field following the pressure wave will also vary inversely with distance from the bubble.

If you want to reproduce the initialization from the article, you need to use the `EntireDomainWithParticularities` domain, to uncomment the first point `//1. Laplace pressure initialization` within the `GDEntireDomainWithParticularities.cpp` file, to adapt this point appropriately, and to compile again.
You have to go through this process since it is very difficult task to make the initial condition file able to reproduce such a pressure field (use of functions within the XML file).

Let me know if it is all clear.

Best,
Kevin

**Comment by NiruBhai** [comment]
Dear Kevin,

Then I guess ignoring the initial timestamps will do. Thank you!

Regards
Niranjan
