### ISSUE TITLE
Unstructured 3D test case didn't work

### ISSUE THREAD

**Issue by wsz1117** [code-mphi/ECOGEN#35]
Hello,

The 3D unstructured test case can not work normally. And we saw the case that water flows in a cylinder in the document. Is that mean the release version can only solve single-phase problem in 3D unstructured domain?

Best wishes

**Comment by wsz1117** [comment]
Nonphysical phenomenon even CFL=0.1
![Screenshot_20230310_165502](https://user-images.githubusercontent.com/75551185/224270231-18f90711-ec82-4e63-8f95-56b322c6f50c.png)

**Comment by kevinschmidmayer** [comment]
Hello,

The release version can solve both single-phase and multiphase problems in 3D with an unstructured mesh. We tried the reference test case and didn't experience any problem. Could you please explain in detail what you are doing and when the first signs of a problem appear?

Best regards,
Kevin

**Comment by wsz1117** [comment]
Dear Kevin Schmidmayer,

No code in .xml file is changed, and the .msh mesh file is uploaded below. 
[bean3D.txt](https://github.com/code-mphi/ECOGEN/files/10978662/bean3D.txt)
![Screenshot_20230315_182114](https://user-images.githubusercontent.com/75551185/225283052-e6130a1d-ccc4-400d-a834-b826d8f1e415.png)

**Comment by kevinschmidmayer** [comment]
I just tried your mesh with 4 CPUs as you did and I got the same problem. However, I don't have the same .msh file generated from GMSH (number of nodes differs). In my case, it works for 1, 3 or 4 CPUs. So my guess is that your mesh is the problem. Although I don't know what happened in order to generate this mesh problem on your end. Try to remesh maybe?

**Comment by kevinschmidmayer** [comment]
Hi, if you don't have any update I will close this issue.
