### ISSUE TITLE
Mesh for 2D axisymmetric gemoetry

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#44]
Dear all,

I am simulating a 2D axisymmetric problem in ECOGEN and using the default cartesian mesh for the same. In solvers like OpenFOAM or ANSYS, the mesh has a wedge shape with one cell thickness, which is visible in the visuals. In ECOGEN though, such a wedge shape geometry is not visible. Instead, I only see a 2D rectangular slice. Could anyone please clarify what is happening?

Regards
Niranjan

**Comment by kevinschmidmayer** [comment]
Dear NiruBhai,

I'm sorry but I am not sure to understand what you are referring to in other solvers. A simulation using 2D axi-symmetry is a 2D simulation (rectangular in the case of a Cartesian mesh) where additional axi-symmetric terms are solved to represent a 3D flow. For this you need an axis of revolution. So that a half 2D bubble with axi-symmetry represents a complete 3D bubble, for example. Is is clearer now?

Best,
Kevin

**Comment by NiruBhai** [comment]
Dear Kevin,

I was referring to this setting (https://doc.cfd.direct/notes/cfd-general-principles/axisymmetric-wedge-condition), which as you made it clear is not the case with ECOGEN. Anyways my doubt is cleared, thank you!

Regards,
Niranjan

![image](https://github.com/user-attachments/assets/c0a40219-c68d-4a11-b56c-190b40ba1c03)
