### ISSUE TITLE
Muticomponent or n phase simulation

### ISSUE THREAD

**Issue by tripatmn** [code-mphi/ECOGEN#46]
Hi, 

I have been trying to explore the capabilities of ECOGEN and wanted to use a mutlicomponent gas and/or 3 phases. I have not found an example that addresses this topic. I was wondering how this will work with the multiphase VOF solver because that range is 0 to 1. 

If numPhases = 3 (2 gas and 1 liquid) how does one go about defining alpha or is there another tracker ?

Thanks.

**Comment by kevinschmidmayer** [comment]
Hi @tripatmn,

ECOGEN uses diffuse interface methods (DIM) and not VOF. In DIM, we solve multiphase models. This means that the sum of the volume of all the phases occupies the whole volume, i.e. $\sum_k \alpha_k = 1$. So as long as your input respects this condition, it should work.

Hope it helps.

Best,
Kevin

**Comment by tripatmn** [comment]
So does this mean the transport (color) function should also be 2?  or does that stay 1?

Thanks

**Comment by kevinschmidmayer** [comment]
I don't think I understand your question. Do you mean the volume fraction of a phase or a color function to track something in specific (no physical meaning of it) ? As I said above, the volume fraction ($\alpha$) should be between 0 and 1. A color function, however, can be of any value since there is no physical meaning of it. Although, we usually also set it up between 0 and 1 for convenience.

**Comment by tripatmn** [comment]
Okay, got it. thank you for your help

**Comment by kevinschmidmayer** [comment]
You're welcome.

Best,
Kevin
