### ISSUE TITLE
Conductivity

### ISSUE THREAD

**Issue by jr144393** [code-mphi/ECOGEN#6]
Is the conductivity module functional?

**Comment by kevinschmidmayer** [comment]
Thermal conductivity had been implemented and should work. Though, I never tested it as much as one should do because we never used it in our contexts/simulations: (very) fast phenomena compared to thermal dissipation. The later is the reason why thermal conductivity is not yet properly presented in the documentation.
Unfortunately, I won't have time to test this in a near future. However, if you spend time on it, I will be interested to have your precise feedback on the matter.
Furthermore, you can find information on the model formulation of the thermal conductivity in https://arc.aiaa.org/doi/abs/10.2514/6.2016-4269.
Thanks.

**Comment by Matshishkapeu** [comment]
I confirm that conduction is partially usable in the last code version. It is possible to add the XML node
`<additionalPhysic type="conductivity"/>` in the "modelV4.xml" input file. This will work if all materials eos files are equipped with the *physicalParameters* XML node including *lambda* attribute. For exemple add the node `<physicalParameters lambda="0.0262"/>`.

This option is not documented yet and here are restrictions for now:
* This option is only possible for the "Kapila" model.
* Boundary conditions are adiabatic.

This can be coupled with the relaxation process **PT** (see [documentation](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_2model.html#relaxation-procedures) for details.)
