### ISSUE TITLE
ECOGEN is not producing .vtk file

### ISSUE THREAD

**Issue by syam-s** [code-mphi/ECOGEN#8]

**Comment by syam-s** [comment]
The ECOGEN test case did not produce any .vtk file for visualization, but I found  .gnu file in the results folder.

**Comment by kevinschmidmayer** [comment]
Hi,
We can only advise you to read the documentation where you will find the responses of your demands: https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/index.html
Thanks

**Comment by kevinschmidmayer** [comment]
Else, to respond to your last question, please look at the format attribute in the output-mode option within the _MainV5.xml_ file of your test case and choose _XML_ instead of _GNU_: https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_1main.html

**Comment by syam-s** [comment]
Thank you for the reply. The results file not contain any collectionParaview.pvd and collectionVisIt.visit file since it was mentioned that those file will be generated after compilation (https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap4_1startWithECOGEN.html#sec-tuto-default)

**Comment by syam-s** [comment]
I found that by changing output-mode option from  "GNU" to "XML" both collectionParaview.pvd and collectionVisIt.visit were generated. Thank you for you response. It will great if you could mention this in the documentation.

**Comment by kevinschmidmayer** [comment]
First, I don't think we mention anywhere that any result files are generated after compilation since it doesn't make sense. They can only be generated after execution.
Second, the output-mode options are mentioned in the documentation (by the way it is done several times and among them in the page I sent you). Please read the documentation carefully.
Thanks.
